Автор материала: Зраев Артем.

Можно использовать в каких угодно целях.

<b> В задании нужно загрузить датасет с данными оттока и ответить на несколько вопросов (написать код). При этом сам датасет уже есть и его необязательно качать с репозитория</b>

Цель задания: проверить базовые навыки работы студентов с Pandas, умение проводить такой же базовый EDA (exploratory data analysis), делать feature engineering и обучать и валидировать модель.

Список столбцов с типами данных в датасете:

- customerID           object
- gender               object
- SeniorCitizen         int64
- Partner              object
- Dependents           object
- tenure                int64
- PhoneService         object
- MultipleLines        object
- InternetService      object
- OnlineSecurity       object
- OnlineBackup         object
- DeviceProtection     object
- TechSupport          object
- StreamingTV          object
- StreamingMovies      object
- Contract             object
- PaperlessBilling     object
- PaymentMethod        object
- MonthlyCharges      float64
- TotalCharges         object
- Churn                object

In [155]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings('ignore')

my_path = r'C:\Users\Pavel\4.1_MachineLearningInBusiness\data\\'

df = pd.read_csv(my_path + 'WA_Fn-UseC_-Telco-Customer-Churn.csv')
df.head(10)

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   
5  9305-CDSKC  Female              0      No         No       8          Yes   
6  1452-KIOVK    Male              0      No        Yes      22          Yes   
7  6713-OKOMC  Female              0      No         No      10           No   
8  7892-POOKP  Female              0     Yes         No      28          Yes   
9  6388-TABGU    Male              0      No        Yes      62          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   
5               Yes     Fiber optic             No  ...              Yes   
6               Yes     Fiber optic             No  ...               No   
7  No phone service             DSL            Yes  ...               No   
8               Yes     Fiber optic             No  ...              Yes   
9                No             DSL            Yes  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   
5          No         Yes             Yes  Month-to-month              Yes   
6          No         Yes              No  Month-to-month              Yes   
7          No          No              No  Month-to-month               No   
8         Yes         Yes             Yes  Month-to-month              Yes   
9          No          No              No        One year               No   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  
5           Electronic check          99.65         820.5   Yes  
6    Credit card (automatic)          89.10        1949.4    No  
7               Mailed check          29.75         301.9    No  
8           Electronic check         104.80       3046.05   Yes  
9  Bank transfer (automatic)          56.15       3487.95    No  

[10 rows x 21 columns]

##### 1. Какое соотношение мужчин и женщин в представленном наборе данных?

In [86]:
df['gender'].value_counts(dropna=False)

Male      3555
Female    3488
Name: gender, dtype: int64

In [87]:
df['gender'].describe()

count     7043
unique       2
top       Male
freq      3555
Name: gender, dtype: object

In [88]:
total_count = df['gender'].describe()['count']
male_rate = df['gender'].describe()['freq'] / total_count
print(f'В представленном наборе данных, из общего количества клиентов = {total_count} человек, {male_rate:2.2%} мужчин и {1-male_rate:2.2%} женщин.')

В представленном наборе данных, из общего количества клиентов = 7043 человек, 50.48% мужчин и 49.52% женщин.


In [89]:
# dct = {'Male' : 1, 'Female' : 0}
# df['gender'] = df['gender'].map(dct)
# df['gender'].unique()

In [90]:
# df.head()

##### 2. Какое количество уникальных значений у поля InternetService?

In [91]:
df['InternetService'].unique()

array(['DSL', 'Fiber optic', 'No'], dtype=object)

In [92]:
print("В поле 'InternetService' {} уникальных значения.".format(len(df['InternetService'].unique())))

В поле 'InternetService' 3 уникальных значения.


##### 3. Выведите статистики по полю TotalCharges (median, mean, std).

In [93]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [94]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'].str.replace(' ', '0'))
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
dtype: object

In [95]:
print('median = {:.2f}, mean = {:.2f}, std = {:.2f}'.format(df['TotalCharges'].median(), df['TotalCharges'].mean(), df['TotalCharges'].std()))

median = 1394.55, mean = 2279.73, std = 2266.79


В чем странность того, что вы получили? (подсказка: смотреть нужно на тип данных) - ПРОЧИТАЛ УЖЕ ПОСЛЕ ТОГО КАК СДЕЛАЛ...

##### 4. Сделайте замену значений поля PhoneService  на числовые (Yes->1, No->0)

In [96]:
dct = {'Yes' : 1, 'No' : 0}
df['PhoneService'] = df['PhoneService'].map(dct)
df['PhoneService'].unique()

array([0, 1], dtype=int64)

In [97]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure  PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1             0   
1  5575-GNVDE    Male              0      No         No      34             1   
2  3668-QPYBK    Male              0      No         No       2             1   
3  7795-CFOCW    Male              0      No         No      45             0   
4  9237-HQITU  Female              0      No         No       2             1   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges  Churn  
0           Electronic check          29.85         29.85     No  
1               Mailed check          56.95       1889.50     No  
2               Mailed check          53.85        108.15    Yes  
3  Bank transfer (automatic)          42.30       1840.75     No  
4           Electronic check          70.70        151.65    Yes  

[5 rows x 21 columns]

##### 5. Сделайте замену пробелов в поле TotalCharges на np.nan и приведите поле к типу данных float32. Затем заполните оставшиеся пропуски значением 0 с помощью метода fillna у столбца. Снова выведите статистики и сравните с тем, что вы видели в вопросе 3

In [98]:
# df.dtypes

In [99]:
# df['TotalCharges'] = df['TotalCharges'].replace(' ', np.nan).astype(np.float32)
# df.dtypes

In [100]:
# df.info()

In [101]:
# row_with_nan_cells = list(df[df['TotalCharges'].isna() == True].index)
# row_with_nan_cells

In [102]:
# df['TotalCharges'] = df['TotalCharges'].fillna(0)
# df.loc[row_with_nan_cells, 'TotalCharges']

In [103]:
# print('median = {:.2f}, mean = {:.2f}, std = {:.2f}'.format(df['TotalCharges'].median(), df['TotalCharges'].mean(), df['TotalCharges'].std()))

#### Получил результат аналогичный результату к заданию № 3.

##### 6. Сделайте замену значений поля Churn на числовые (Yes -> 1, No - 0)

In [104]:
dct = {'Yes' : 1, 'No' : 0}
df['Churn'] = df['Churn'].map(dct)
df['Churn'].unique()

array([0, 1], dtype=int64)

In [105]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure  PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1             0   
1  5575-GNVDE    Male              0      No         No      34             1   
2  3668-QPYBK    Male              0      No         No       2             1   
3  7795-CFOCW    Male              0      No         No      45             0   
4  9237-HQITU  Female              0      No         No       2             1   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges  Churn  
0           Electronic check          29.85         29.85      0  
1               Mailed check          56.95       1889.50      0  
2               Mailed check          53.85        108.15      1  
3  Bank transfer (automatic)          42.30       1840.75      0  
4           Electronic check          70.70        151.65      1  

[5 rows x 21 columns]

##### 7. Сделайте замену значений полей StreamingMovies, StreamingTV, TechSupport  на числовые (Yes -> 1, No -> 0, No internet service->0)

In [106]:
df['StreamingMovies'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [107]:
df['StreamingTV'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [108]:
df['TechSupport'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [109]:
dct = {'Yes': 1, 'No': 0, 'No internet service': 0}
df['StreamingMovies'] = df['StreamingMovies'].map(dct)
df['StreamingMovies'].unique()

array([0, 1], dtype=int64)

In [110]:
df['StreamingTV'] = df['StreamingTV'].map(dct)
df['StreamingTV'].unique()

array([0, 1], dtype=int64)

In [111]:
df['TechSupport'] = df['TechSupport'].map(dct)
df['TechSupport'].unique()

array([0, 1], dtype=int64)

In [112]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure  PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1             0   
1  5575-GNVDE    Male              0      No         No      34             1   
2  3668-QPYBK    Male              0      No         No       2             1   
3  7795-CFOCW    Male              0      No         No      45             0   
4  9237-HQITU  Female              0      No         No       2             1   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport  StreamingTV  StreamingMovies        Contract PaperlessBilling  \
0           0            0                0  Month-to-month              Yes   
1           0            0                0        One year               No   
2           0            0                0  Month-to-month              Yes   
3           1            0                0        One year               No   
4           0            0                0  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges  Churn  
0           Electronic check          29.85         29.85      0  
1               Mailed check          56.95       1889.50      0  
2               Mailed check          53.85        108.15      1  
3  Bank transfer (automatic)          42.30       1840.75      0  
4           Electronic check          70.70        151.65      1  

[5 rows x 21 columns]

##### 8. Заполните пропуски в поле PhoneService значением 0

In [113]:
df['PhoneService'].unique()

array([0, 1], dtype=int64)

In [114]:
df['PhoneService'].count()

7043

In [115]:
df['PhoneService'].value_counts(dropna=False)

1    6361
0     682
Name: PhoneService, dtype: int64

#### Пропусков нет

#### 8. Для нашего датасета оставьте только указанный ниже список полей, удалив все другие и выведите верхние 3 строки

In [116]:
columns = ['gender', 'tenure', 'PhoneService', 'TotalCharges', 
           'StreamingMovies', 'StreamingTV', 'TechSupport', 'Churn']

df = df[columns]
df.head(3)

gender  tenure  PhoneService  TotalCharges  StreamingMovies  StreamingTV  \
0  Female       1             0         29.85                0            0   
1    Male      34             1       1889.50                0            0   
2    Male       2             1        108.15                0            0   

   TechSupport  Churn  
0            0      0  
1            0      0  
2            0      1

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 8 columns):
gender             7043 non-null object
tenure             7043 non-null int64
PhoneService       7043 non-null int64
TotalCharges       7043 non-null float64
StreamingMovies    7043 non-null int64
StreamingTV        7043 non-null int64
TechSupport        7043 non-null int64
Churn              7043 non-null int64
dtypes: float64(1), int64(6), object(1)
memory usage: 440.3+ KB


##### 9. Разделите датасет на тренировочную и тестовую выборку (подсказка - воспользуйтесь train_test_split из sklearn.model_selection. Ссылка - https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html)

In [118]:
from sklearn.model_selection import train_test_split

features = ['gender', 'tenure', 'PhoneService', 'TotalCharges', 'StreamingMovies', 'StreamingTV', 'TechSupport']
target = 'Churn'
X_train, X_test, y_train, y_test = train_test_split(df[features], df[target], random_state=42)

##### 10. соберите pipeline для поля gender (нужно разобраться и изучить https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html ) из классов ColumnSelector и OHEEncoder, которые уже написаны ниже заранее

In [119]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline

class ColumnSelector(BaseEstimator, TransformerMixin):
    """
    Transformer to select a single column from the data frame to perform additional transformations on
    """
    def __init__(self, key):
        self.key = key

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        return X[self.key]
    
# class NumberSelector(BaseEstimator, TransformerMixin):
#     """
#     Transformer to select a single column from the data frame to perform additional transformations on
#     Use on numeric columns in the data
#     """
#     def __init__(self, key):
#         self.key = key

#     def fit(self, X, y=None):
#         return self

#     def transform(self, X):
#         return X[[self.key]]
    
class OHEEncoder(BaseEstimator, TransformerMixin):
#     def __init__(self, key):
    def __init__(self):
#         self.key = key
#         self.columns = []
        pass

    def fit(self, X, y=None):
#         self.columns = [col for col in pd.get_dummies(X, prefix=self.key).columns]
#         self.columns = pd.get_dummies(X, prefix=self.key).columns
        return self

    def transform(self, X):
#         X = pd.get_dummies(X, prefix=self.key)
#         test_columns = [col for col in X.columns]
#         for col_ in test_columns:
#             if col_ not in self.columns:
#                 X[col_] = 0
#         return X[self.columns]
#         return pd.get_dummies(X, prefix=self.key)
        return pd.get_dummies(X)

gender = Pipeline([
    ('selector', ColumnSelector(key=['gender'])),
#     ('ohe', OHEEncoder(key='gender'))
    ('ohe', OHEEncoder())
])

##### 11. Вызовите метод fit_transform у пайплайна gender и передайте туда нашу тренировочную выборку (пример по ссылке из документации https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html#sklearn.pipeline.Pipeline.fit)

In [120]:
# проверка
gender.fit_transform(X_train)

gender_Female  gender_Male
6607              0            1
2598              1            0
2345              1            0
4093              1            0
693               1            0
...             ...          ...
3772              0            1
5191              1            0
5226              0            1
5390              0            1
860               0            1

[5282 rows x 2 columns]

##### 12. Здесь код писать уже не нужно (все сделано за вас). К полю tenure применяем StandardScaler (нормируем и центрируем). Ссылка - https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html
Вопрос - в каких случаях это может быть полезно? - чтобы данные были одного порядка, т.е. центрированы относительно 0 с дисперсией равной 1.

In [131]:
from sklearn.preprocessing import StandardScaler

tenure = Pipeline([('selector', ColumnSelector(key=['tenure'])),
                   ('standard', StandardScaler())
                   ])

##### 13. Напишите аналогичный (как для tenure) преобразователь поля TotalCharges

In [132]:
total_charges = Pipeline([('selector', ColumnSelector(key=['TotalCharges'])),
                          ('standard', StandardScaler())
                          ])

In [125]:
number_features = Pipeline([
    ('selector', ColumnSelector(key=['PhoneService', 'StreamingMovies', 'StreamingTV', 'TechSupport']))
])

Объединение всех "кубиков" очень легко сделать таким образом

In [133]:
from sklearn.pipeline import FeatureUnion

feats = FeatureUnion([
    ('tenure', tenure),
    ('TotalCharges', total_charges),
    ('continuos_features', number_features),
    ('gender', gender)
])

feature_processing = Pipeline([('feats', feats)])

In [134]:
# проверка
feature_processing.fit_transform(X_train)

array([[-1.28288214, -0.99706554,  0.        , ...,  0.        ,
         0.        ,  1.        ],
       [-1.03785653, -0.77679441,  1.        , ...,  0.        ,
         1.        ,  0.        ],
       [-1.16036933, -0.97052898,  1.        , ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [-0.83366851, -0.87330905,  1.        , ...,  0.        ,
         0.        ,  1.        ],
       [-0.83366851, -0.47918373,  1.        , ...,  0.        ,
         0.        ,  1.        ],
       [-0.26194207, -0.80663703,  1.        , ...,  0.        ,
         0.        ,  1.        ]])

На этом этапе что мы сделали:
1. написали преобразователь поля gender, который делает OHE кодирование
2. написали преобразователь для поля tenure, который нормирует и центрирует его 
3. повторили п. 2 для поля TotalCharges
3. для всех остальных просто взяли признаки как они есть, без изменений

У нас уже готов наш пайплайн, который преобразовывает признаки. Давайте обучим модель поверх него. В качестве модели возьмем RandomForestClassifier

In [135]:
from sklearn.ensemble import RandomForestClassifier

pipeline = Pipeline([
    ('features',feats),
    ('classifier', RandomForestClassifier(random_state = 42)),
])

pipeline.fit(X_train, y_train)

Pipeline(memory=None,
     steps=[('features', FeatureUnion(n_jobs=None,
       transformer_list=[('tenure', Pipeline(memory=None,
     steps=[('selector', ColumnSelector(key=['tenure'])), ('standard', StandardScaler(copy=True, with_mean=True, with_std=True))])), ('TotalCharges', Pipeline(memory=None,
     steps=[('selector',...mators=10, n_jobs=None,
            oob_score=False, random_state=42, verbose=0, warm_start=False))])

##### 14. Сделайте прогноз вероятности оттока для X_test с помощью нашего предобученного на предыдущем шаге пайплайна и убедитесь что вам возвращаются вероятности для 2 классов

In [146]:
y_pred = pipeline.predict_proba(X_test)
y_pred[:10]

array([[0.1       , 0.9       ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.        , 1.        ],
       [0.9       , 0.1       ],
       [0.8       , 0.2       ],
       [0.7       , 0.3       ],
       [1.        , 0.        ],
       [0.7       , 0.3       ],
       [0.60666667, 0.39333333]])

In [143]:
y_test[:10]

185     1
2715    0
3825    0
1807    1
132     0
1263    1
3732    0
1672    0
811     1
2526    1
Name: Churn, dtype: int64

##### 15. Посчитайте метрики качества получившейся модели (roc_auc, logloss)

In [148]:
from sklearn.metrics import roc_auc_score, log_loss

roc_auc_score(y_test, y_pred[:, 1])

0.7638337475043888

In [149]:
log_loss(y_test, y_pred)

2.2768499274362557

### Сохраним наш пайплайн

In [154]:
import dill
with open(my_path + 'model_RF.dill', 'wb') as f:
    dill.dump(pipeline, f)